### ISSUE TITLE
Reconsider milestone/version/release handling

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#988] opened 2017-02-18 12:23 UTC
Extracted from #955. Assumes we're switching to GitFlow.

I think we'll need to overhaul our "next release" workflow. It's been a little problematic anyhow, I think, since we've been guessing about our next release version and then renaming or replacing milestones and releases and build issues. Let's see how we can improve things, especially now that GitFlow has more to say about releases than does GitHubFlow.
I see a few paths forward. I'm open to incremental improvements, so we could consider some or all of what I talk about below. My biases abound. I'm sure there are more options. 

* We can work essentially as we've been doing, except not assign versions to milestones, releases, and release issues. We could make placeholders for "next release" and assign specific version names when we need them (when we create a release branch). When we create a hotfix branch, we will also create a new set of these things. In that case, they can be tied to a version right away.

And now I get more radical.

* I generally find the way we use milestones to be nothing but overhead. We work by marking an issue in-progress, and then when it's done, we add it to the release. Once we release, the milestone provides no value at all. I'd consider ditching milestones. We could reserve them for special cases, like "breaking issues to go in the next major" or "things that have to go in 4.0, even though that release isn't on the horizon (like removing Self-Initializing Fakes)", but I think we could get along without them just about all the time
* I've long thought we should keep release notes in an `.md` file in the repo. As soon as a PR that's releasenotable is merged (or as part of the PR, if the contributor is savvy), we update the file with the release note (and thanks to the contributors). If we do this, we could make our "release" step generate the GitHub release from that file. We could do this manually at first, but I've been toying with the idea of a tool that'll scrape the file and create the GitHub Release. (Longer term, _I'd_ like to see this file be the source of our current version number, but that's slightly more involved as well and, I imagine, contentious. Let's forget I said it for now.)

**Comment by blairconrad** [comment] 2017-02-18 12:28
In #955, @thomaslevesque [said](https://github.com/FakeItEasy/FakeItEasy/issues/955#issuecomment-269323418)

----
> The first is that we can work essentially as we've been doing, except not assign versions to milestones, releases, and release issues. We could make placeholders for "next release" and assign labels when we need them (when we create a release branch). When we create a hotfix branch, we will also create a new set of these things. In that case, they can be tied to a version right away.

I like this option; it's easy and not too disruptive.

> I generally find milestones to be nothing but overhead. We work by marking an issue in-progress, and then when it's done, we add it to the release. Once we release, the milestone provides no value at all. I'd consider ditching milestones. We could reserve them for special cases, like "breaking issues to go in the next major" or "things that have to go in 4.0, even though that release isn't on the horizon (like removing Self-Initializing Fakes)", but I think we could get along without them just about all the time

I kind of like milestones. It makes it easier to see where we're headed, what goes in the next release, etc

> I've long thought we should keep release notes in an .md file in the repo. As soon as a PR that's releasenotable is merged (or as part of the PR, if the contributor is savvy), we update the file with the release note (and thanks to the contributors). If we do this, we could make our "release" step generate the GitHub release from that file. We could do this manually at first, but I've been toying with the idea of a tool that'll scrape the file and create the GitHub Release. (Longer term, I'd like to see this file be the source of our current version number, but that's slightly more involved as well and, I imagine, contentious.)

It's an interesting idea. However, if this file is going to contain the whole history of release notes, parsing it won't be trivial.

For now, I'd vote for the first option. We can always take some of your other ideas later if we want.

**Comment by thomaslevesque** [comment] 2017-02-18 14:01
> We can work essentially as we've been doing, except not assign versions to milestones, releases, and release issues. We could make placeholders for "next release" and assign specific version names when we need them (when we create a release branch). When we create a hotfix branch, we will also create a new set of these things. In that case, they can be tied to a version right away.

:+1:

> I generally find the way we use milestones to be nothing but overhead. We work by marking an issue in-progress, and then when it's done, we add it to the release. Once we release, the milestone provides no value at all. I'd consider ditching milestones. We could reserve them for special cases, like "breaking issues to go in the next major" or "things that have to go in 4.0, even though that release isn't on the horizon (like removing Self-Initializing Fakes)", but I think we could get along without them just about all the time

I've already answered that comment, but looking at it again, I think the problem is not milestones themselves but the way we use them. Things could work more smoothly with your proposal of just creating a "vNext" placeholder milestone.

**Comment by adamralph** [comment] 2017-02-25 00:16
I don't really mind if the next milestone is called `vNext` or `3.1.0`. With the former, we'll *always* need to rename it, but with the latter we'll only have to rename it if we decide to release a bug fixes only, and we've already assigned a bug fix to the next milestone. So, potentially slightly less to do if it's called `3.1.0` but I really don't mind.

> Once we release, the milestone provides no value at all...

I'm not sure this is true. We can filter issues by milestone. It's true that the release notes do contain a list of all the issues closed in a milestone, but this is an alternative view where the issue labels can also be seen. Perhaps that isn't a great deal of added value but it may be _some_ added value.

However, I'm also not sure that we're making the most use of milestones. We merge a fair amount of refactoring/tech-debt PRs and we do not mark those against milestones. We only mark those issues which are going to be in the release notes against milestones (and hence the degree of redundancy). In some other projects I'm involved in (the NServiceBus ones, mainly) we do mark these kinds of non-functional change PR's against milestones. Sometimes it's useful to know in which version these kind of changes were made, e.g. when tracking down a bug, or when back porting a bug fix (or even feature) to an older version. We don't do much of the latter, but we do fix bugs and sometimes it's useful to know what refactorings, etc. may have caused the bug.

**Comment by thomaslevesque** [comment] 2017-02-25 15:03
> I'm not sure this is true. We can filter issues by milestone. It's true that the release notes do contain a list of all the issues closed in a milestone, but this is an alternative view where the issue labels can also be seen. Perhaps that isn't a great deal of added value but it may be some added value.

In fact, I use the milestones to make sure nothing is missing in the release notes.

**Comment by blairconrad** [comment] 2017-02-26 02:12
> I don't really mind if the next milestone is called vNext or 3.1.0.

My understanding is that [under GitFlow](http://nvie.com/posts/a-successful-git-branching-model/#release-branches)

> It is exactly at the start of a release branch that the upcoming release gets assigned a version number—not any earlier. Up until that moment, the develop branch reflected changes for the “next release”, but it is unclear whether that “next release” will eventually become 0.3 or 1.0

"vNext" seems to match this spirit better.

> In some other projects I'm involved in (the NServiceBus ones, mainly) we do mark these kinds of non-functional change PR's against milestones

That's fine by me. In fact, I'd even be up for mentioning these things in the release notes, at least when the changes are contributed by a community member, if only as an opportunity to give credit where it's due. Either way, adding them to the milestone sounds good.

**Comment by blairconrad** [comment] 2017-06-13 10:16
I think we've accomplished the goals of this issue. We're putting "additional items" in the milestones and release notes, and we recently updated our release checklist to call the next release "vNext", until we know what it will be released as.

Okay to close?

**Comment by thomaslevesque** [comment] 2017-06-13 10:22
:+1:

**Closed** 2017-06-13 10:46 UTC
Labels: build, discussion
