### ISSUE TITLE
An argument constraint, such as That, Ignored, or _, cannot be nested in an argument.

### ISSUE THREAD

**Issue by SebastianStehle** [FakeItEasy/FakeItEasy#1239] opened 2017-10-18 05:55 UTC
I upgraded FakeItEasy to the newest version and the following call fails now:

    A.CallTo(() => usageStore.TrackUsagesAsync(A<DateTime>.Ignored, A<string>.Ignored, A<double>.Ignored, A<long>.Ignored)).MustNotHaveHappened();

with a `System.InvalidOperationException : An argument constraint, such as That, Ignored, or _, cannot be nested in an argument.`

We also upgraded a project at work and had the same problem there. Both calls have in common that all method arguments are ignored.

**Comment by SebastianStehle** [comment] 2017-10-18 06:58
It turned out that we used the wrong type. In this case long instead of double. But the error message has potential for improvements.

**Comment by thomaslevesque** [comment] 2017-10-18 07:33
Hi @SebastianStehle,

This has already been reported in #1230, and has been fixed. It was indeed related to implicit conversions in the expression. The fix will be in the next release.

Thanks!

**Comment by thomaslevesque** [comment] 2017-10-18 07:33
Duplicate of #1230

**Closed by thomaslevesque** 2017-10-18 07:33 UTC
