### ISSUE TITLE
Cannot fake types implementing IDisposable

### ISSUE THREAD

**Issue by shortsn** [FakeItEasy/FakeItEasy#440] opened 2015-01-22 16:01 UTC
**Update by @adamralph**

See https://github.com/FakeItEasy/FakeItEasy/issues/440#issuecomment-71312010. When a type implements `IDisposable` correctly, and that type is faked, the call to `virtual Dispose(false)` from the finalizer of the type causes an `ArgumentException` to be thrown.

----

Hi there,
yesterday we updated from FakeItEasy 1.14.0 to FakeItEasy 1.25.1.
Now we have several errors during our unit-test teardown.
We pointed out that the error occurs when calling any faked method in an object finalizer.

```csharp
internal class Program {
		private static void Main(string[] args) {
			new Foobar(A.Fake<IDisposable>());
			GC.Collect();
			GC.WaitForPendingFinalizers();
		}
	}

	internal class Foobar : IDisposable {
		private readonly IDisposable _something;
		private bool _disposed;

		public void Dispose() {
			Dispose(true);
			GC.SuppressFinalize(this);
		}

		~Foobar() {
			Dispose(false);
		}

		public Foobar(IDisposable something) {
			_something = something;
		}

		protected virtual void Dispose(bool free_managed) {
			if (_disposed) {
				return;
			}

			if (free_managed) {
			}
			_something.Dispose();
			_disposed = true;
		}
	}
```

![error](https://cloud.githubusercontent.com/assets/6273088/5859101/14d7c586-a258-11e4-8cda-2163e203d19b.PNG)

**Comment by adamralph** [comment] 2015-01-22 16:18
@shortsn thanks for raising this.

I noticed a flaw in your current implementation. You should only be calling `_something.Dispose()` when `free_managed` is `true`, since `_something` is a managed resource. If you make that change, do you still have the same problem?

**Comment by shortsn** [comment] 2015-01-22 16:32
hi @adamralph,
i just used my disposable snippet to build the sample code. You are right handling it as managed would help in this case but any usecase where _something is not a managed resource i still have the same problem.

**Comment by adamralph** [comment] 2015-01-22 16:39
A fake can never be an unmanaged resource. It's a CLR object so therefore it's managed.

The concrete implementation (not the fake) may well release unmanaged resources internally, but that's not a concern for your testing, since you're faking that implementation.

**Comment by adamralph** [comment] 2015-01-22 16:43
Or rather, your injected `_something` is, by definition (it is a CLR type), a managed resource. Your implementation of `Foobar` is flawed by calling `_something.Dispose()` in the finalizer.

**Comment by shortsn** [comment] 2015-01-22 19:22
Ok your suggestion may solve our problem. On one hand it was quiet hard to figure out the source of the problem because the exception text wasn't very helpful. On the other hand i still don't understand what the exception is telling me about the fake objects state.

**Comment by adamralph** [comment] 2015-01-22 19:53
I need the full stack trace to analyse what's happening, but in any case, it's really a moot point. There's little value in investing time into making FakeItEasy support operations from within a finalizer.

**Comment by blairconrad** [comment] 2015-01-23 01:06
@shortsn, I believe I know what's happening. The message is new in 1.25.1 (technically 1.25.0, but close enough) and came with #373. It's to do with the new "handle virtual calls in constructor" functionality. It indicates that the fake (or "proxy") that's being called, in this case `_something`, is not the same as the fake that the proxy's `FakeManager` knows about.

Let me continue to explain.

Each fake is tagged with a `FakeManager` instance, whose responsibility it is to intercept all the calls and take care of the configuration of the fake and whatnot.
The FakeManager in turn has a weak reference back to the fake.
By the time the everything's being garbage collected and finalized, the FakeManager's weak reference to the fake is not longer "alive", so the reference looks like a null.
So when the `Dispose` method is called, the fake and the null are compared. The fake isn't null, so the exception is thrown.

Given that all this is happening when everything's being finalized, at this point I agree with @adamralph: I don't see much value in running around trying to support the operation, especially since, in the only instance we've seen of this happening, it's arguably as a result of a logic error.

**Comment by danm-de** [comment] 2015-01-23 20:56
Hi,

First I have to say I love FakeItEasy and I really appreciate your work!

I admit that the disposable pattern hasn't been implemented right in shortsn's example. However, there are some use cases that do not work anymore:
- If you try to mock/fake PInvoke calls (that usually allocate unmanaged memory) - it is a common practice to start cleanups in the finalizer (just to be safe if the "user" did not call Dispose())
- If you work with and/or wrap third party libraries. You cannot change their "bad" behavior.
- If your class does logging / perf measuring / .. in the finalizer (e.g. https://gist.github.com/danm-de/d898262145f07beb86e9)

Of course you can work around the problem by keeping references to all fake instances and use "strict fakes" by default. :-(

It was very(!) hard to identify the cause of error. What do you think about enriching the exception message with some hints about GC+finalizer calls? That could possibly protect users (like me) from spending hours of debugging time after nuget update-package ;-)

**Comment by blairconrad** [comment] 2015-01-23 21:33
Thanks for chiming in, @danm-de, and I (for one) am glad you enjoy FakeItEasy.

The issue is clearly more complicated than we thought. You make a good point about 3rd party libraries, and we do realize that it's not always practical to say "this is how things _should_ work".

Can you explain about mocking PInvoke calls? I'm not a big PInvoker, but every time I have, I end up getting static methods, which are unfakeable.

I'm also a little confused about the example in your gist. It seems to me to be a very bad idea to try to use a log object from within a finalizer, since there's no guarantee that the log object wouldn't already have been finalized. IMO, this is a logical error.

I'm not sure how "strict fakes" help here. Can you explain?

All that out of the way, it seems we have more thinking to do about it. Regarding your suggestion about enhancing the log message, I think that may be premature. If this behaviour is affecting people when finalizers are used properly, perhaps we can do better than augmenting a log message.
As it turns out, I'm currently looking at an issue that's near the relevant section of code, so I'll see what I can figure out.

**Comment by danm-de** [comment] 2015-01-23 23:22
Hi @blairconrad, 

Thanks for your fast reply.

Often you need slightly different PInvoke calls for x86 (32bit) and x64 (64bit) platforms - OR - different operating systems like Windows or Linux. I usually create an adapter for each platform that implements one common/public interface. This adapter ONLY wraps the static methods - it doesn't do any memory management. Faking the adapter interface gives me the possibility to actually "fake" Windows/Linux API calls. In the finalizer/Dispose method I often have something like this:
```c#
if (_allocatedUnmanagedMemory != IntPtr.Zero) {
	_adapter.Free(_allocatedUnmanagedMemory);
	Trace.Assert(disposing, "ERROR: GC finalized unmanaged memory ...");
}
```

The code in the gist was just an abstract example to show what I've seen in various projects (without any judgment whether it is a good idea or not :-) 

I have just learned a lesson:

_The finalizers of two objects are not guaranteed to run in any specific order, even if one object refers to the other. That is, if Object A has a reference to Object B and both have finalizers, Object B might have already finalized when the finalizer of Object A starts._

https://msdn.microsoft.com/de-de/library/system.object.finalize%28v=vs.110%29.aspx

(Thanks for pointing out that mistake! :-)

Forget my suggestion holding references to fake instances and use strict fakes - it does not work.

**Comment by blairconrad** [comment] 2015-01-24 00:35
@danm-de regarding the PInvoke wrapper: got it. Thanks. I should've thought of this application, as it's the sort of approach I often recommend for decoupling static methods :blush:

In that case, the nondeterministic finalizer order probably would not be a problem on its own.

I'll look for some time over the weekend to see if I can find other approaches.
In the meantime, is rolling back to 1.24.0 an option for you? You'd only be losing out on optional `Now` and `Go` when raising events, and #368. If you recently moved up to 1.25.1, I doubt you'd miss these features much…

**Comment by adamralph** [comment] 2015-01-24 08:11
I'm still not convinced of the need to support this (although I'm happy to be convinced :wink:).

As I understand it (reading https://msdn.microsoft.com/en-us/library/fs2xkftw%28v=vs.110%29.aspx), there are two patterns for implementing disposable types. In the first, the unmanaged resources are freed directly in the type itself, using pinvoke or whatever mechanism is appropriate. In the other, these resources are wrapped in types implementing `SafeHandle`. In the former, you would not be faking anything when testing the type, since the type itself is coupled to the unmanaged resources and therefore would only lend itself to a black box style test. In the latter, you would never invoke the finalizers of the `SafeHandle` derived types from your code, since that is left to the CLR.

**Comment by shortsn** [comment] 2015-01-24 11:23
Hi guys,

at first i would like say that i also really like the framework and thank you for this interesting discussion.
Maybe i can describe 2 additional usecases:

```javascript
public abstract class SomeServiceBase : IDisposable {
	public void Dispose() {
		Dispose(true);
		GC.SuppressFinalize(this);
	}

	~SomeServiceBase() {
		Dispose(false);
	}

	protected virtual void Dispose(bool free_managed) {}
}

class SomeServiceImpl : SomeServiceBase {}
```

1. Lets assume that i have an abstract base implementation of a service which provides the default disposable pattern and some other fancy standard functions i want to inherit. In the test for another component i would like to provide this default behavior by injecting a faked instance of ```A.Fake<SomeServiceBase>() ```

2. Another example could be some kind of acceptance test with a more complex user scenario where i want to assert the order of specific method calls. Here it is sometimes easier to inject a wrapped instance than faking the required behavior. ```A.Fake<SomeServiceBase>(options => options.Wrapping(new SomeServiceImpl())); ```

Due to the virtual dispose method both examples are leading to the discussed problem.

**Comment by blairconrad** [comment] 2015-01-24 14:13
@adamralph, I may have some ideas that can convince you that doing _something_ is worthwhile. Will expand in a few hours, with luck.
@shortsn, running out the door. Will read later!

Now that you're on tenterhooks, I will make my dramatic exit!

**Comment by blairconrad** [comment] 2015-01-24 21:52
Okay. That took longer than expected.

@shortsn, I'm sorry, but I'm going to need you to explain in a little more detail. I can't see how the default disposable pattern would cause a problem, with wrapping or without. In either case, the finalizer would call `Dispose(false)`, and thereby not invoke any of the methods on managed objects. Only if calls to managed objects are being made inside `Dispose(false)` would you run into problems.
Perhaps you have a complete example that would clear things up for me?

**Comment by adamralph** [comment] 2015-01-24 22:21
@shortsn thank you too for the discussion. It's certainly interesting and I known I've already benefited from it.

At the moment, I'm with @blairconrad on this. I'm still not seeing a situation in which a CLR object should be invoked from a finalizer. I believe doing so is fundamentally incorrect, given the way garbage collection works. I.e. for given set of objects, the timing and order of their garbage collection is non-deterministic and may vary wildly between executions.

**Comment by blairconrad** [comment] 2015-01-24 22:21
@shortsn, scratch my earlier comment. I got it. The virtual `Dispose` is called from the Finalizer. Even if we do nothing bad in there when the argument is `false` FakeItEasy will encounter the error when it compares the fake to the FakeManager's `Object`.

**Comment by adamralph** [comment] 2015-01-24 22:28
Ah, I see too. So this is a different problem, but I guess with the same cause? I.e. this is not about calling fake dependencies within finalizers anymore, but rather the call from the finalizer of a wrapped object to the virtual `Dispose` of the fake? That does seem like a genuine problem.

**Comment by blairconrad** [comment] 2015-01-24 22:34
Indeed. Or even a non-wrapped fake!

**Comment by adamralph** [comment] 2015-01-24 22:39
OK, shall we spin off a separate bug with an appropriate title and description or shall we keep things here? If keeping here I guess we should probably edit the title and insert an update into the top of the description so that's clear what's being fixed?

**Comment by blairconrad** [comment] 2015-01-24 22:39
I think keeping things here is fine. Title and update up to sound good to me.

**Comment by blairconrad** [comment] 2015-01-24 22:40
My suggested fix(es) will be coming in a few minutes!

**Comment by blairconrad** [comment] 2015-01-24 22:48
Back to my promised update for @adamralph!

As I mentioned before, `FakeManagerProvider.Fetch` compares the incoming proxy with the initialized FakeManager object to make sure we're not calling `Fetch` and passing in the wrong proxy. It was something that @ulrichb introduced in #373.
I remember a comment during the PR, but can't find it, about how this check was essentially to guard against future programmer error. I thought it might have been excessive, but did not predict any harm. *ahem*

Anyhow, `Fetch` is called in only two places - during method interception for DynamicProxy fakes and Delegate fakes, and I see no way to mess it up.
If the manager's object isn't the same as the passed-in fake, we shouldn't have passed the check in `RuleMatcher.Matches`, so I'm not sure how we'd get to method interception.

So, I think that we can dispense with the check. Alternatively, we could additionally check that the manager's `Object` isn't `null`, since that's the problem we're facing when the call comes out of a Finalizer.
(I've not yet tried this, but could give it a whirl this weekend.)

I'd be inclined to put this in milestone 1.25.2.

**Comment by adamralph** [comment] 2015-01-24 22:48
I'm still digesting, but yes, I'm thinking we should push out 1.25.2 rather than delay until 2.0.

**Comment by adamralph** [comment] 2015-01-24 23:14
@blairconrad what you describe sounds reasonable.

Right now my main concern is how to write a failing test for this before we fix it. Perhaps something like this would work?

```C#
var fake = A.Fake<SomeDisposable>();
GC.Collect(); // kill unrooted objects without finalizers and add pointers to those with finalizers to the freachable queue
GC.WaitForPendingFinalizers(); // wait for the finalization thread to excute the finalizers and clear the freachable queue
GC.Collect(); // kill all remaining unrooted objects 
fake.SomeMethod(); // keep the fake rooted during the above GC's
GC.Collect(); // add a pointer to the fake to the freachable queue
GC.WaitForPendingFinalizers(); // wait for the fake to be finalized
```

**Comment by blairconrad** [comment] 2015-01-24 23:22
@adamralph, the test may very well work. Until we try, we won't know. :wink:
Did you want to try to fix this one, or would you like me to? I'm content to do, and figure you have more bau/xbehave.net work, but am happy either way.

**Comment by adamralph** [comment] 2015-01-24 23:28
@blairconrad no, I've no preference. You seem to have a good handle on the fix so please go ahead. I'll keep my finger poised on the merge button...

**Comment by adamralph** [comment] 2015-01-25 07:48
Closed by #444

**Closed** 2015-01-25 07:48 UTC
Labels: 3 - Done, bug, P1

**Comment by adamralph** [comment] 2015-01-25 07:53
@shortsn the patch will be released shortly. Do you have a Twitter handle? We'd like to give you a mention to express our gratitude for raising this bug.

**Comment by shortsn** [comment] 2015-01-25 08:58
Wow, @adamralph @blairconrad thank you for fixing this so fast. My twitter name is @sh0rtsn.
Have a nice day.

**Comment by blairconrad** [comment] 2015-01-25 11:57
@shortsn, thanks very much for your work on this issue. Look for your name in the release notes. :trophy:

This issue has been fixed in release 1.25.2.

https://www.nuget.org/packages/FakeItEasy/1.25.2
https://github.com/FakeItEasy/FakeItEasy/releases/tag/1.25.2

**Comment by blairconrad** [comment] 2015-01-25 16:24
@shortsn, it's a pleasure to _be able_ to resolve something so quickly. Assuming it works for you, of course.
Thanks for raising the issue.
Oh, and @danm-de, thanks for chiming in.

**Comment by danm-de** [comment] 2015-01-25 18:27
Nice! That was fast, thanks!

**Comment by blairconrad** [comment] 2015-01-25 19:14
No problem, @danm-de. The hard part is convincing us (especially me) that something is _worth_ doing. :stuck_out_tongue_winking_eye:
