### ISSUE TITLE
Release 6.0.0-beta.1

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1671] opened 2019-10-23 11:07 UTC
- [x] Address all coding and style violations detected during a *Release* build (send a regular pull request which must be merged before continuing)
- [x] ensure completeness of draft [release notes](https://github.com/FakeItEasy/FakeItEasy/releases), including non-owner contributors, if any (move release notes forward from any pre-releases to the current release)
- before releasing 6.0.0, check integration package compatibility
  - [ ] [AutoFixture.AutoFakeItEasy](https://github.com/AutoFixture/AutoFixture) - @blairconrad
        broken by _ReturnValue not set #1696_, released in 5.4.1. `SetReturnValue` is no longer found by `FakeObjectCall`.
  - [x] [Machine.Fakes.FakeItEasy](https://github.com/machine/machine.fakes)
  - [x] [Autofac.Extras.FakeItEasy](https://github.com/autofac/Autofac.Extras.FakeItEasy)   
  - [x] [EntityFrameworkTesting.FakeItEasy](https://github.com/scott-xu/EntityFramework.Testing)
- [x] run `tools\prepare_release.cmd next x.y.z vNext` to:
    - change "vNext" names to appropriate x.y.z version for the next GitHub Release, milestone, and release checklist (this issue)
    - create a new draft GitHub Release, milestone, and release checklist
- [x] tag master with the new version number and push to upstream. This will cause the build server to
    - push the nupkgs to [nuget.org](https://www.nuget.org/profiles/FakeItEasy),
    - attach all nupkgs from the tagged build to the GitHub Release,
    - add a comment to each issue and pull request in the release, saying it was published in this release
- [x] wait for NuGet package validation
- [x] de-list pre-release NuGet packages if present
- [x] publish the GitHub release
- [x] tweet, mentioning contributors, and post link as comment here for easy retweeting ;-)
- [x] post tweet in [Gitter](https://gitter.im/FakeItEasy/FakeItEasy)
- [x] add a note in each issue that has a significant contribution from a community member, thanking the contributor
- [x] close this issue
- [x] if this is **not** a pre-release, close the [milestone](https://github.com/FakeItEasy/FakeItEasy/milestones?state=open) for this release

**Comment by blairconrad** [comment] 2019-12-05 12:01
#1690 is nearly complete, and this was the last issue that we'd listed as a must-have for the 6.0.0 release. Once it's merged, I'd like to issue a beta.1 release, if that's okay.
We _could_ try upgrading the Octokit and NuGet versions before this. Worst case, the release fails.

**Comment by thomaslevesque** [comment] 2019-12-05 13:25
> Once it's merged, I'd like to issue a beta.1 release, if that's okay.

Works for me.

> We _could_ try upgrading the Octokit and NuGet versions before this. Worst case, the release fails.

I'm not very worried about NuGet. Octokit, I don't know, but I guess that if the code still compiles, the behavior probably won't have changed. Is there a benefit to upgrading, or is it just for the sake of upgrading?

**Comment by blairconrad** [comment] 2019-12-05 14:14
>  is it just for the sake of upgrading

Yeah. Which is part of the reason I hadn't pushed it yet. I'm content to leave them as they are until we run into trouble.

**Comment by thomaslevesque** [comment] 2019-12-05 14:24
I don't mind either way. If you feel like upgrading, go ahead

**Comment by blairconrad** [comment] 2019-12-05 14:27
Nah, it's good. My stress level rises every time we jiggle the deploy tool.

**Comment by thomaslevesque** [comment] 2019-12-19 11:26
https://twitter.com/fakeiteasyfx/status/1207622933574823936

**Closed** 2019-12-19 11:39 UTC
Labels: build, documentation

**Comment by TimLovellSmith** [comment] 2019-12-20 20:11
FYI I tried out the 6.0.0 beta, and found no regressions, tests, continued to run pretty fast, but .... our overall build time went up noticably! My hunch is that this is most likely to be a size-of-files, times number of times we have to copy/load/crossref them thing related to Castle.Core packaging.

**Comment by blairconrad** [comment] 2019-12-20 20:28
Glad there were no regressions, @TimLovellSmith. I'm a little surprised about the build time changes. Which TFM are you using?
