### ISSUE TITLE
Add a FakeItEasy.FSharp package

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#232] opened 2014-01-09 11:49 UTC
Spun off from https://github.com/FakeItEasy/FakeItEasy/issues/229#issuecomment-31921208

Will include similar extensions to http://trelford.com/blog/post/MoqEx.aspx

More examples:

``` csharp
//C#
A.CallTo(() => comparer.Compare(
    A<string>._,
    A<string>.That.Matches(s => s == "must be equal to this"))).Returns(-1);
```

``` fsharp
//F#
A.CallTo(fun () -> comparer.Compare(ignored(), is((=) "must be equal to this"))).Returns(-1)
```

``` csharp
//C#
A.CallTo(() => factory.Create()).Returns(A.Fake<IWidget>());
```

``` fsharp
//F#
A.CallTo(fun () -> factory.Create()).Returns(fake())
```

We should add a `FakeItEasy.FSharp` project to FakeItEasy.sln and ensure it gets built, packaged and released along with the other projects.

As for testing, an acceptance test project is probably enough. I don't think unit tests would add much value.

The test project layout and naming convention is a little messy right now. What is under the `Integration Tests` solution folder right now is generally anything that is not unit tests. Perhaps the test project should be `Integration Tests\FakeItEasy.FSharp.Tests.Acceptance`.

I've no idea what test framework would be suitable for F#. Currently we use NUnit (which we're considering replacing with xunit.net) and MSpec.

**Comment by thomaslevesque** [comment] 2016-08-29 18:16
I thought it would be pretty easy, and I tried this in LinqPad:

```
open FakeItEasy

let ignored<'a>() = A<'a>.Ignored

let is<'a> f = A<'a>.That.Matches(fun x -> f x)

let comparer = A.Fake<IComparer<string>>()
A.CallTo(fun () -> comparer.Compare(ignored(), is((=) "must be equal to this"))).Returns(-1)
comparer.Compare("test", "hello").Dump()
```

But unfortunately it throws _"The specified object is not recognized as a fake object."_. I suspect F# overload resolution doesn't work the same way as in C# (which isn't very surprising, since F# itself doesn't support overloading), and it resolves `A.CallTo(object)` rather than `A.CallTo(Expression<Func<int>>)`. As @ptrelford noted in [this SO answer](http://stackoverflow.com/a/32081081/98713), it works with unnatural fakes, because they don't have an overload taking an `object` (they have an `AnyCall()` method instead).

I tried to force it to pick the right overload, but didn't succeed (maybe because of my limited knowledge of F#).

So unless I'm missing something, it looks like FIE's natural fakes are not compatible with F#...

**Comment by thomaslevesque** [comment] 2016-08-29 18:25
The best I managed to do is this:

```
open FakeItEasy
open Microsoft.FSharp.Linq.RuntimeHelpers

let ignored<'a>() = A<'a>.Ignored

let is<'a> f = A<'a>.That.Matches(fun x -> f x)

let toExpression (quotation : Quotations.Expr<'a>) =
    let body = LeafExpressionConverter.QuotationToExpression quotation
    Expression.Lambda<Func<'a>>(body)

let toVoidExpression (quotation : Quotations.Expr) =
    let body = LeafExpressionConverter.QuotationToExpression quotation
    Expression.Lambda<Action>(body)

let calling quotation = A.CallTo(toExpression quotation)
let callingVoid quotation = A.CallTo(toVoidExpression quotation)

let comparer = A.Fake<IComparer<string>>()
calling(<@ comparer.Compare(ignored(), is((=) "hello")) @>).Returns(-1)
callingVoid(<@ comparer.ToString() @>).Throws(new Exception("oops"))
comparer.Compare("test", "hello").Dump()
comparer.ToString().Dump()
```
But the API isn't as nice...

**Comment by thomaslevesque** [comment] 2017-11-23 20:33
> F# itself doesn't support overloading

I was mistaken. F# *functions* don't support overloading, but *methods* can be overloaded. So we can do something like this instead:

```fsharp
open FakeItEasy
open Microsoft.FSharp.Linq.RuntimeHelpers

module FakeItEasyFSharp =

    let private toExpression (quotation : Quotations.Expr<'a>) =
        let body = LeafExpressionConverter.QuotationToExpression quotation
        Expression.Lambda<Func<'a>>(body)

    let private toVoidExpression (quotation : Quotations.Expr) =
        let body = LeafExpressionConverter.QuotationToExpression quotation
        Expression.Lambda<Action>(body)
        
    let ignored<'a>() = A<'a>.Ignored

    let is<'a> f = A<'a>.That.Matches(fun x -> f x)

    type A with
        static member CallTo(quotation: Quotations.Expr<'a>) = A.CallTo(toExpression quotation)
        static member CallTo(quotation: Quotations.Expr) = A.CallTo(toVoidExpression quotation)
```

Which can be used as follows:

```fsharp
open FakeItEasyFSharp

type IMyInterface =
    abstract Foo : unit -> unit

type IMyFactory =
    abstract Create : unit -> IMyInterface

let comparer = A.Fake<IComparer<string>>()
A.CallTo(<@ comparer.Compare(ignored(), is((=) "foo")) @>).Returns(-1) |> ignore
A.CallTo(<@ comparer.ToString() @>).Throws(new Exception("oops")) |> ignore

let factory = A.Fake<IMyFactory>()
A.CallTo(<@ factory.Create() @>).Returns(fake()) |> ignore
```

This covers all the use cases mentioned by @adamralph, although the syntax is a bit different. Apparently it should be possible to use lambdas instead of quotations, but I couldn't make it work. But I think I prefer quotations anyway, the `fun () ->` part just adds noise.

The `|> ignore` isn't absolutely necessary, but without it the compiler emits a warning, because the return value isn't used.

We could also consider adding functions like `returns` or `throws` to make the syntax more idiomatic; for instance:

```
let comparer = A.Fake<IComparer<string>>()
A.CallTo(<@ comparer.Compare(ignored(), is((=) "foo")) @>) |> returns -1 |> ignore
A.CallTo(<@ comparer.ToString() @>) |> throws (new Exception("oops")) |> ignore
```
The problem is that the `Returns` and `Throws` methods have multiple overloads, so if we want to map them to F# functions, we need to pick a different name for each overload.

Anyway, if we attempt to make a FakeItEasy.FSharp package, we should probably get some F# experts to review the proposed API.

**Comment by thomaslevesque** [comment] 2017-11-23 20:46
OK, apparently my approach isn't perfect yet... `A.CallTo(<@ foo.VoidMethod() @>)` still picks the overload with `Quotations.Expr<'a>` (where `'a` is `unit`; F# doesn't really have the notion of `void`). So we would need a method with a different name for configuring void methods, which is annoying... In this case, there's no real point in using methods rather than functions, since the whole point was to allow overloads.

**Comment by thomaslevesque** [comment] 2017-11-23 21:16
Alternative implementation, a bit more complete, and more idiomatic:

```
open FakeItEasy
open FakeItEasy.Configuration
open Microsoft.FSharp.Linq.RuntimeHelpers

module FakeItEasyFSharp =

    let private toExpression (quotation : Quotations.Expr<'a>) =
        let body = LeafExpressionConverter.QuotationToExpression quotation
        Expression.Lambda<Func<'a>>(body)

    let private toVoidExpression (quotation : Quotations.Expr) =
        let body = LeafExpressionConverter.QuotationToExpression quotation
        Expression.Lambda<Action>(body)

    let fake<'a>() = A.Fake<'a>()

    let aCallTo (quotation: Quotations.Expr<'a>) = A.CallTo(toExpression quotation)
    let aCallToVoid (quotation: Quotations.Expr) = A.CallTo(toVoidExpression quotation)
    let anyCallTo(fake: Object) = A.CallTo(fake)

    let ignored<'a>() = A<'a>.Ignored
    let is<'a> f = A<'a>.That.Matches(fun x -> f x)
    
    let returns (value:'a) (configuration: IReturnValueConfiguration<'a>) = configuration.Returns(value)
    let throws (ex: Exception) (configuration: IExceptionThrowerConfiguration<'a>) = configuration.Throws(ex)
    let doesNothing (configuration: IDoNothingConfiguration<'a>) = configuration.DoesNothing()
    let invokes (callback: (unit -> unit)) (configuration: ICallbackConfiguration<'a>) = configuration.Invokes(fun () -> callback())
```
Usage:

```
open FakeItEasyFSharp
#nowarn "20"

type IFoo =
    abstract Bar : unit -> unit
    abstract Baz : string -> int

type IFooFactory =
    abstract Create : unit -> IFoo

let comparer = A.Fake<IComparer<string>>()
aCallTo <@ comparer.Compare(ignored(), is((=) "foo")) @> |> returns -1 |> ignore
aCallToVoid <@ comparer.ToString() @> |> throws (Exception("oops")) |> ignore

let factory = A.Fake<IFooFactory>()
let foo = fake()
aCallTo <@ factory.Create() @> |> returns(foo)
anyCallTo foo |> throws (NotImplementedException())
aCallToVoid <@ foo.Bar() @> |> invokes (fun () -> printfn "hello")
```

**Comment by blairconrad** [comment] 2024-04-10 19:15
We're very unlikely to implement the package described in this issue. The core maintainers have neither motivation nor expertise. Closing. Should sufficient interest arrive, we could reopen.

**Closed by blairconrad** 2024-04-10 19:15 UTC
Labels: :checkered_flag: ready, :rocket: enhancement
