### ISSUE TITLE
Allow configuration of hidden (by new) members on classes

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1346] opened 2018-05-09 13:22 UTC
Consider:

```c#
[Fact]
public void EverythingOkTest()
{
    var derivedFake = A.Fake<Derived>();
    Base baseFake = derivedFake;

    A.CallTo(() => baseFake.Method()).Returns("configured hidden method");

    Assert.Equal("configured hidden method", baseFake.Method());
}

public class Base
{
    public virtual string Method() => throw new Exception(nameof(Base));
}

public class Derived: Base
{
    public virtual new string Method() => throw new Exception(nameof(Derived));
}
```

I'd've expected the same as if `Base` and `Derived` were interfaces - that the test would pass. Instead, it throws `"Base"`, even though we're configuring `Base.Method`.

Found while working on https://github.com/AutoFixture/AutoFixture/pull/1025.

**Comment by thomaslevesque** [comment] 2018-05-12 10:14
Enhancement ? I would have called it a bug... The fact that `Derived.Method` hides `Base.Method` should have no effect in this case.

**Comment by blairconrad** [comment] 2018-05-12 10:28
I struggle with the categorized. I've no problem with bug. Rebranding.

**Comment by blairconrad** [comment] 2018-06-17 01:05
I mentioned that this came up during my work on AutoFakeItEasy. @zvirja actually asked about the behaviour in https://github.com/AutoFixture/AutoFixture/pull/1025#discussion_r186121911.
I'm struggling. Dynamic proxy does not intercept the hidden methods, and I don't see a way to configure it to do so.
Even manually overriding the hidden method escapes me.
@zvirja, have you seen intercepting/overriding a hidden method work, either in a Dynamic Proxy client or otherwise?

**Comment by thomaslevesque** [comment] 2018-06-17 14:43
> Dynamic proxy does not intercept the hidden methods, and I don't see a way to configure it to do so.

Same here. Looks like it isn't possible at all. I'd be tempted to call it a bug in Castle.Core.

**Comment by zvirja** [comment] 2018-06-17 15:03
@thomaslevesque @blairconrad Thanks for investigation and registrations of the issue! Let's see what Castle project says.

As for other mock libraries (NSubstitute, Moq), honestly, I'm not sure about their behavior :disappointed: But I'm pretty confident they also suck as they also rely on the Castle under the hood...

CC @stakx

**Comment by thomaslevesque** [comment] 2018-06-17 15:15
> As for other mock libraries (NSubstitute, Moq), honestly, I'm not sure about their behavior 😞 But I'm pretty confident they also suck as they also rely on the Castle under the hood...

NSubstitute exhibits the same issue as FakeItEasy. Moq doesn't provide a way to configure `Base.Method`, as far as I can tell (but I don't know Moq very well).

**Comment by thomaslevesque** [comment] 2018-06-17 15:35
> According to this issue they don't support hidden methods intentionally: moq/moq4#22

That issue is about interfaces, not classes. In FakeItEasy, you can configure a hidden method of an interface, the issue only exists for classes.

**Comment by stakx** [comment] 2018-06-17 15:44
As to Moq, the exact example above isn't supported, but this sort of works for interfaces:

```csharp
public interface IBase
{
    string Method();
}

public interface IDerived : IBase
{
    new string Method();
}

[Fact]
public void EverythingOkTest()
{
    var derivedMock = new Mock<IDerived>();
    var baseMock = derivedMock.As<IBase>();
    baseMock.Setup(m => m.Method()).Returns("configured hidden method");
    Assert.Equal("configured hidden method", fakeMock.Object.Method());
}
```

You can also set up both the method in `IBase` and `IDerived` differently, so I'd say DynamicProxy generally allows this kind of thing.

To be honest, though, method shadowing/overriding is one aspect of .NET Reflection, LINQ expression trees, DynamicProxy, and Moq that I personally struggle to wrap my head around everytime I need to think about it. Moq's logic for identifying the correct method to set up in such a situation has developed over time, and it works more thanks to trial-and-error (IIRC) than by careful rigorous application of the CLR rules. It's one part of Moq that should be reworked someday. It also doesn't help that the C# compiler often unexpectedly puts the "wrong" (base) `MethodInfo`s in an expression tree, meaning you need to second-guess expressions and try to adjust them to what the user meant to do.

Anyways, I'll take a look at what you posted over at DynamicProxy. I'd be a little surprised if it didn't support this scenario.

**Comment by thomaslevesque** [comment] 2018-06-17 15:58
> I'd be a little surprised if it didn't support this scenario.

In fact, I'm pretty sure it doesn't. The root of the problem is [here](https://github.com/castleproject/Core/blob/69598068cabe759c62f894f6a1e9974772f58ef7/src/Castle.Core/DynamicProxy/Generators/MethodFinder.cs#L48). It removes duplicates by identical signature, so it only gets the first method (`Type.GetMethods` returns the most derived method first).

In a way, I guess it makes sense: in C#, you can't override a hidden base class method, i.e a class `Derived2` that inherits `Derived` could override `Derived.Method`, but not `Base.Method`. If the CLR itself allows it, it might be possible for Castle.Core to do it, but I'm not sure how useful it would be.

**Comment by thomaslevesque** [comment] 2018-06-17 16:02
> If the CLR itself allows it

In fact, I think it does. If you just change the return type of `Derived.Method`, the signature is no longer considered identical, and Castle.Core can intercept both. It also works as expected with FakeItEasy.

**Comment by stakx** [comment] 2018-06-17 16:21
> If the CLR itself allows it

I don't think it does. The CLR has its own rules about method shadowing, and once you introduce (via `newslot`) a new method in `Derived` that has the exact same signature as the one in `Base`, you won't get to choose in `.class EvenMoreDerived extends Derived` which of these to override&mdash;you'll only see the one from `Derived`, just like in C#.

**Comment by thomaslevesque** [comment] 2018-06-17 16:49
Given what I found (https://github.com/castleproject/Core/issues/381#issuecomment-397890953), I guess you're correct, @stakx.

**Comment by blairconrad** [comment] 2018-06-17 22:15
Was away from computer all day. I appreciate you guys doing all my work for me!

**Comment by thomaslevesque** [comment] 2018-06-20 10:00
As discussed with @stakx, there's no way to do it; it's not even because of Castle.Core, it's a CLR limitation. Closing.

**Closed by thomaslevesque** 2018-06-20 10:00 UTC
Labels: :beetle: bug, P2
