### ISSUE TITLE
Support for PCL

### ISSUE THREAD

**Issue by godrose** [FakeItEasy/FakeItEasy#630] opened 2016-03-24 06:54 UTC
The package does not have compatible libraries. When trying to install the rc1 the error message is displayed : "Can't find compatible packages blah-blah-blah".

**Comment by blairconrad** [comment] 2016-03-24 10:18
@godrose, thanks for your interest. Unfortunately, [it's not possible for FakeItEasy to support PCL](https://github.com/FakeItEasy/FakeItEasy/issues/214#issuecomment-59406766), since we depend on Castle.Core's `DynamicProxy` to generate our proxy ("fake") classes, and Castle.Core doesn't support PCL, nor will it, according to castleproject/Core#41.

As much as we'd like to help, I think this issue has to be closed "wontfix".

**Comment by godrose** [comment] 2016-03-24 10:23
Cool.
I guess all dynamic-proxy-dependent frameworks won't make it to the world of UWP and vNext.
Manual proxies it is, then!

Thanks for your reply.

**Comment by blairconrad** [comment] 2016-03-24 10:26
Oh, we do plan to support .NET Core. See #531.

**Comment by godrose** [comment] 2016-03-24 11:19
Glat to hear that. Any timeline?

**Comment by blairconrad** [comment] 2016-03-24 14:07
Not as such. As you can see, we've outside help working on #531, but it will ultimately depend on progress in Castle.Core, and of course on the shifting state of .NET Core itself.

**Comment by blairconrad** [comment] 2016-03-24 14:08
This is essentially a duplicate of #531 at this point. Closing.

**Closed by blairconrad** 2016-03-24 14:08 UTC
Labels: duplicate
