### ISSUE TITLE
Mutating an object parameter erases all history for CallTo assertions

### ISSUE THREAD

**Issue by cable729** [FakeItEasy/FakeItEasy#965] opened 2017-01-11 17:20 UTC
If I have a method I'm testing that updates the same object multiple times and overwrites fields, I can't test each call to that method, because the calls are using the same object, and mutating it. FakeItEasy doesn't clone objects and only keeps a handle to the reference, so calls early on will be mutated when the service mutates that object.

Here is an example of a test that does not seem like it should fail, but it does (FakeItEasy 2.3.2 and XUnit 2.1.0 on .NET 4.5.2 and Windows 10)

```c#
using FakeItEasy;
using Xunit;

namespace FakeItEasyExample
{
    public interface IUserRepository
    {
        User Update(User user);
    }

    public class User
    {
        public int FavoriteNumber { get; set; }
    }

    public class UserService
    {
        private readonly IUserRepository _repository;

        public UserService(IUserRepository repository)
        {
            _repository = repository;
        }

        public void ChangeFavoriteNumber(User user)
        {
            user.FavoriteNumber++;
            _repository.Update(user);

            user.FavoriteNumber++;
            _repository.Update(user);
        }
    }

    public class UserServiceTests
    {
        [Fact]
        public void IncrementingTwiceFromZeroShouldUpdateWithOne()
        {
            var repo = A.Fake<IUserRepository>();
            var service = new UserService(repo);
            var user = new User {FavoriteNumber = 0};

            service.ChangeFavoriteNumber(user);

            A.CallTo(() => repo.Update(A<User>.That.Matches(u => u.FavoriteNumber == 1))).MustHaveHappened();
        }
    }
}
```

Exception:
```
FakeItEasy.ExpectationException


  Assertion failed for the following call:
    FakeItEasyExample.IUserRepository.Update(<u => (u.FavoriteNumber == 1)>)
  Expected to find it at least once but found it #0 times among the calls:
    1: FakeItEasyExample.IUserRepository.Update(user: FakeItEasyExample.User) repeated 2 times
    ...


   at FakeItEasy.Core.FakeAsserter.AssertWasCalled(Func`2 callPredicate, String callDescription, Func`2 repeatPredicate, String repeatDescription) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeAsserter.cs:line 32
   at FakeItEasy.Configuration.RuleBuilder.MustHaveHappened(Repeated repeatConstraint) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 109
   at FakeItEasyExample.UserServiceTests.IncrementingTwiceFromZeroShouldUpdateWithOne() in c:\users\caleb\documents\visual studio 2015\Projects\FakeItEasyExample\FakeItEasyExample\UserServiceTests.cs:line 45
```

**Comment by blairconrad** [comment] 2017-01-11 17:47
@cable729, what you say is absolutely true. Unfortunately, this is essentially a duplicate of #306 (which points at a StackOverflow question that suggests a workaround.)

I doubt we'll see any change around this, but if someone comes up with a great idea, we'd be keen to hear it. If you want to pursue the issue, I recommend doing so over at #306.

**Comment by blairconrad** [comment] 2017-01-11 17:47
Closing as duplicate of #306.

**Closed by blairconrad** 2017-01-11 17:47 UTC
Labels: duplicate

**Comment by thomaslevesque** [comment] 2017-01-11 17:54
Hi @cable729,

In order to make your assertion work, FakeItEasy would need to be able to check if the argument matched the constraint *at the time of the call*, but since the assertion is made *after* the call, there's no way to know in advance what the assertions will be. The only way make this work would be to clone the arguments of each call when the call is recorded, to have a "snapshot" of the arguments against which the constraints could be evaluated. But if we did that, another very common scenario would no longer work:

    A.CallTo(() => repo.Update(user)).MustHaveHappened();

because the recorded value for the argument would now be a clone of the original `user`, so reference comparison would return false.

As far as I can tell, there is no way to make both scenarios work, so I think we should support the most common one.

**Comment by blairconrad** [comment] 2017-01-11 17:57
@thomaslevesque an excellent point!

**Comment by cable729** [comment] 2017-01-11 18:07
Thanks for the quick response. I've actually tried that workaround and using `.Invokes()` causes `.Returns()` to not work and just return `null`. I'll try to recreate a small example again and post it. Is this something you've seen before?

**Comment by blairconrad** [comment] 2017-01-11 19:06
@cable729, thanks for asking. Sounds like #830, which is fixed in 3.0.0-beta001. Would you consider picking it up and trying?

**Comment by thomaslevesque** [comment] 2017-01-11 19:06
> Thanks for the quick response. I've actually tried that workaround and using .Invokes() causes .Returns() to not work and just return null. I'll try to recreate a small example again and post it. Is this something you've seen before?

Could you show what you tried exactly?

The fact that it returns null is a known issue (#830), which is fixed in the upcoming 3.0.0 version. However that wouldn't be enough to make your workaround work.

If you're doing something like this:

```
bool callHappened = false;
A.CallTo(() => repo.Update(A<User>.Ignored)).Returns(user);
A.CallTo(() => repo.Update(A<User>.That.Matches(u => u.FavoriteNumber == 1))).Invokes(() => callHappened = true);
```

note that the second configuration overrides the first (when the argument matches the constraint), so the first configuration has no effect.

**Comment by cable729** [comment] 2017-01-13 22:24
Is that intended behavior for `Invokes` to override `Returns`? I would like to be able to do both, actually.

**Comment by blairconrad** [comment] 2017-01-14 00:56
@cable729, `Invokes` is not supposed to override `Returns`.

@thomaslevesque's comment about the second configuration line above overriding the first when the argument matches the constraint describes a feature of how call specification works in general in FakeItEasy, and isn't specific to `Invokes` and `Returns`, or in fact any action that you can specify. As noted in [Changing behavior between calls](http://fakeiteasy.readthedocs.io/en/stable/limited-call-specifications/#changing-behavior-between-calls), later call specifications override earlier ones (when the two specifications can apply to the same calls).

By calling `A.CallTo(() => repo.Update(A<User>.Ignored)).Returns(user)`, we create a rule that says that "a call to `repo.Update`, regardless of the passed in `User` object, will return `user`".
When we add `A.CallTo(() => repo.Update(A<User>.That.Matches(u => u.FavoriteNumber == 1))).Invokes(() => callHappened = true)`, we create a rule that will be evaluated before the other one. However, it only applies when the passed-in user's favourite number is 1. In that case, instead of returning `user`, we will invoke the side of setting `callHappened` to `true`. If the user's favorite number is anything else, this rule will not match, and FakeItEasy will keep looking. Then it finds the original rule and will return `user`.
