### ISSUE TITLE
fix up Should_be_able_to_get_a_fake_value_of_uri_type test

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#610] opened 2016-02-23 18:35 UTC
… according to conversation leading up to https://github.com/FakeItEasy/FakeItEasy/pull/606/files#r53825817.

**Comment by blairconrad** [comment] 2016-02-23 18:37
Created in error. @adamralph said he'd send a PR.

**Comment by adamralph** [comment] 2016-02-23 18:37
Since it's here, I'll use it.

**Comment by blairconrad** [comment] 2016-02-23 18:38
That works too.

**Comment by adamralph** [comment] 2016-02-23 19:13
So, I went back to [the commit directly before this test was added](https://github.com/FakeItEasy/FakeItEasy/commit/97a64a334485dd1d5ebfdaa35f112bcb1e8f441b), I then [added only the test](https://github.com/adamralph/FakeItEasy/commit/f1fed14391ab1edcccc9b9475f7873f2c3af3787) and confirmed that it fails. I never saw it actually fail, but the test runner seemed to hang, which confirmed that some kind of infinity is taking place, and that `System.Uri` cannot be faked. I tried with `System.Object` instead and confirmed that the test passes in that case (instantly).

I then [refactored the test to use a custom type](https://github.com/adamralph/FakeItEasy/commit/d56e377b22e261cf494b62f2c23552c01530ebb1) and the refactored version passed!

This means the problem is not as simple as having a type which has a constructor with arguments of that type. It must be something else special about `System.Uri`. Unless @patrik-hagne can shed any more light on the original problem, I propose we just leave the test as-is and close this.

**Comment by blairconrad** [comment] 2016-02-23 19:52
If we were curious, we could debug into the Uri-flavoured test with the original code, so see what happens. But I don't mind closing it.

**Comment by adamralph** [comment] 2016-02-23 20:49
Now I'm curious :wink:

**Comment by patrik-hagne** [comment] 2016-02-23 20:58
Is this something I wrote? I really can't remember anything special about
the Uri-type.

The only real special case I can remember was this interesting thing...
http://stackoverflow.com/questions/2803262/unable-to-catch-exception-from-activator-createinstance
Den 23 feb 2016 21:50 skrev "Adam Ralph" <notifications@github.com>:

> Now I'm curious :wink:

**Comment by adamralph** [comment] 2016-02-25 19:57
I'm still not sure what it is about the Uri type, but here's the repetition in the call stack:

![image](https://cloud.githubusercontent.com/assets/677704/13332460/62ccf0d8-dc02-11e5-8fdf-81422f35997d.png)

**Comment by adamralph** [comment] 2016-02-25 20:04
I'm leaning towards closing and being content that there's *something* strange about `System.Uri` that caused this problem.

**Comment by blairconrad** [comment] 2016-02-25 20:08
No argument here.

**Closed** 2016-02-25 20:20 UTC
Labels: refactoring, wontifx

**Comment by adamralph** [comment] 2016-06-19 14:15
I'm deleting the branch which shows the problem, but for the record, here's the version of the test which fails to demonstrate the mysterious problem with `System.Uri`:

```C#
using NUnit.Framework;
using System;
using FakeItEasy.Core;

namespace FakeItEasy.IntegrationTests
{
    [TestFixture]
    public class FakingClassesTests
    {
        [Test]
        public void Should_be_able_to_get_a_fake_for_a_type_with_a_constructor_taking_arguments_of_that_type()
        {
            using (Fake.CreateScope(new NullFakeObjectContainer()))
            {
                var result = A.Dummy<ConstructsFromCurrentInstances>();
                Console.Write(result);
            }
        }
    }

    public class ConstructsFromCurrentInstances
    {
        public ConstructsFromCurrentInstances()
        {
        }

        public ConstructsFromCurrentInstances(ConstructsFromCurrentInstances firstInstance)
        {
        }
    }
}
```
