### ISSUE TITLE
Flaky tests when run in parallel

### ISSUE THREAD

**Issue by fishie** [FakeItEasy/FakeItEasy#1794] opened 2020-10-20 20:11 UTC
Hello,

We use FakeItEasy, [xUnit](https://github.com/xunit/xunit) and [Rebus](https://github.com/rebus-org/Rebus) at my company. We have some tests that are flaky and I have looked into why this is. My current best guess is that there is some kind of odd problem with concurrency in FakeItEasy which is why I'm creating this bug report. I have been able to reduce our code down to a small toy example that still is flaky [Flaky.zip](https://github.com/FakeItEasy/FakeItEasy/files/5411240/Flaky.zip). I understand that you might not know about Rebus so I will try my best to explain what I think is happening without going into too much unnecessary detail.

We use Rebus.Testhelpers to create a mock version of our "saga". That fake saga receives a command message that it is supposed to handle. The handler for the message changes the state of the fake Saga. Somewhere along the line, the fake Saga tries to clone its state by serializing the "saga data" to JSON and deserializing it back to saga data again. This is where an exception sometimes (!) is thrown which can be seen by going through the LogEvents of the saga. The exception is thrown at this line https://github.com/rebus-org/Rebus.TestHelpers/blob/7ebb5f1b968b34f69dd1afffd55f6197afc103e0/Rebus.TestHelpers/Internals/InMemorySagaStorage.cs#L238.

The exception is:
```
Newtonsoft.Json.JsonSerializationException

Could not find type 'Castle.Proxies.SomeOtherDataProxy' in assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=a621a9e7e5c32e69'.
```
Note again that this happens **sometimes**. When it works, the type is properly set to the real type instead of the proxy type and the deserialization works fine.

This seems like some kind of problem with concurrency. I read up on parallelism in xUnit and sure enough, adding the class attribute `[Collection("Flaky tests")]` to both of the test classes eliminates the flakiness.

Converting the test project to MSTest also eliminates the flakiness. I suspect this is because MSTest does not execute tests in parallel by default.

Commenting out line 12 in MySecondTestClass.cs also eliminates the flakiness.

At this point I'm stuck. I need someone smarter than me to look at this to get any further. Could this be an issue with xUnit? Any help is appreciated, thank you very much :)

**Comment by thomaslevesque** [comment] 2020-10-20 21:11
Hi @fishie,

To be honest, I'm not sure I really understand what's going on here. If JSON.NET was able to serialize the object and emit its type in the JSON, then the type definitely exists... I have no idea why it it's found.

> When it works, the type is properly set to the real type instead of the proxy type

Is it? In the code you sent, `someOtherDataService` isn't configured, so `CreateSomeOtherData` should always return a fake `SomeOtherData`...

I did a quick test in LinqPad, which I believe is equivalent to your scenario:

```csharp
    var sagaData = new MySagaData();
    sagaData.SomeData = new SomeData();
    sagaData.SomeOtherData = A.Fake<SomeOtherData>();
    
    var jsonSettings = new JsonSerializerSettings
    {
        TypeNameHandling = TypeNameHandling.All
    };
    var json = JsonConvert.SerializeObject(sagaData, jsonSettings).Dump();
    var sagaData2 = JsonConvert.DeserializeObject<ISagaData>(json, jsonSettings).Dump();
```

It fails on deserialization with this exception:

- JsonSerializationException: Error resolving type specified in JSON 'Castle.Proxies.SomeOtherDataProxy, DynamicProxyGenAssembly2`
  - FileLoadException: Could not load file or assembly 'DynamicProxyGenAssembly2, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state.
    - InvalidOperationException: Dynamically emitted assemblies are unsupported during host-based resolution.

It's not the exact same exception that you got, but it's similar. Note that there's no concurrency involved in my test.
I think the problem is the way JSON.NET resolves types from the `$type` property.
According to the stack trace, the exception occurs [here](https://github.com/JamesNK/Newtonsoft.Json/blob/666d9760719e5ec5b2a50046f7dbd6a1267c01c6/Src/Newtonsoft.Json/Serialization/DefaultSerializationBinder.cs#L69), and there's some kind of limitation preventing a dynamically emitted assembly from being loaded that way...

**Comment by thomaslevesque** [comment] 2020-10-20 21:23
[Assembly.LoadWithPartialName](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.loadwithpartialname?view=netcore-3.1)

>Loads an assembly from the application directory or from the global assembly cache using a partial name.

So this method clearly cannot load a dynamic assembly, since it's neither on the file system nor in the GAC. So basically, JSON.NET can't handle types in dynamic assemblies.

Of course, that doesn't explain why it works sometimes, and why commenting `A.Fake<object>()` in a completely different test suddenly makes it work...

**Comment by thomaslevesque** [comment] 2020-10-20 21:37
I'm afraid I'm as stuck as you are.

The error you're getting just doesn't make sense:
- During serialization, JSON.NET gets the type of the fake `SomeOtherData` to write it to the JSON.
- That type is "Castle.Proxies.SomeOtherDataProxy" since, as far as I can tell, in your test SomeOtherData is always a fake
- During deserialization, JSON.NET manages to load the DynamicProxyGenAssembly2 assembly (which fails in my own test)
- And then it fails to find the type, even though this type must definitely exist, since it was just used, and written in the JSON...

I honestly have no idea what's going on.

**Comment by fishie** [comment] 2020-10-20 21:44
Very interesting. You are correct that this assumption of mine is incorrect:

> When it works, the type is properly set to the real type instead of the proxy type

I wrote the `serializedObject` from Rebus.TestHelpers to file and compared the output from succesful run to a failed run... and the type always looks like this no matter if succesful run or failed run:

```
    {
        "$type": "MyProject.MySagaData, MyProject",
        "SomeData": {
            "$type": "MyProject.SomeData, MyProject",
            "Id": null
        },
        "SomeOtherData": {
            "$type": "Castle.Proxies.SomeOtherDataProxy, DynamicProxyGenAssembly2"
        },
        "Id": "fff5fdf3-d663-486d-ac2e-3153cf9eaef9",
        "Revision": 0
    }
```

It sounds like it could even be an issue with JSON.NET then, I hadn't even considered that. But yeah, glad I'm not the only one confused. I will go to sleep now maybe I'll have a revelation in my dreams ;)

**Comment by thomaslevesque** [comment] 2020-10-21 07:18
> It sounds like it could even be an issue with JSON.NET then

Or maybe in Castle.Core, or in .NET Core... Or in FakeItEasy, of course!

**Comment by fishie** [comment] 2020-10-21 19:20
True. Seems like it could be anything at this point. Thank you very much for looking into this. It has been very helpful :) You confirmed that I am not crazy and straightened out my misunderstandings about FakeItEasy. I think my plan forward for this is to see if I can remove Rebus out of the equation kind of like how you did and just use JSON.NET to try and recreate the flakiness. If I cannot, see if the Rebus people have an idea, or if Rebus can be removed then maybe someone over at xUnit can help. I will report back if I find anything. I don't have too much time to spend on this and it might take a while so I would like to end with what Churchill always used to say about flaky tests: _[never give in](https://www.youtube.com/watch?v=L90BCEVH41U)_.

**Comment by blairconrad** [comment] 2020-10-21 19:54
Hi, @fishie!

I think removing Rebus is a great first step. I would not go after the xUnit people though, as @thomaslevesque has reproduced without involving xUnit, as I understand it.

Me, I reproduced by eliminating the second test and just putting the `A.Fake<object>()` call early on in the test:

```
[Fact]
public void MyFirstTestMethod()
{
    var o = A.Fake<object>();
    var someDataService = A.Fake<ISomeDataService>();
    var someOtherDataService = A.Fake<ISomeOtherDataService>();
    A.CallTo(() => someDataService.GetSomeData()).Returns(new SomeData());
   …
```

And I'm relatively sure the xUnitiness of it wasn't a factor in this case. I'm lazy, but would consider just making this a console app to verify.

I will have to invoke that Churchill quote at work, as we are plagued by flaky tests.

**Comment by fishie** [comment] 2020-10-23 09:03
Very interesting find @blairconrad. It seems that if I run it like you did, the test is no longer flaky, it consistently fails. That could mean that the reason that my original example is flaky is because sometimes the A.Fake<object>() in the MySecondTestMethod is run before MyFirstTestMethod and sometimes after, thus sometimes failing sometimes passing. I also converted to a console application without xUnit and it also consistently fails like you said. I haven't been able to remove Rebus yet. To be continued.

**Comment by blairconrad** [comment] 2020-12-06 14:12
@fishie , @thomaslevesque , I've continued the investigation a bit. I decided to print out the 2 or 3 faked objects in my test (if I don't fake `<Object>`, my test passes. Here's what I got:

Passing test:
```
someDataService = Castle.Proxies.ObjectProxy: DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
someOtherDataService = Castle.Proxies.ObjectProxy_1: DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
```

Failing test:

```
o = Castle.Proxies.ObjectProxy: DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=a621a9e7e5c32e69
someDataService = Castle.Proxies.ObjectProxy_1: DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
someOtherDataService = Castle.Proxies.ObjectProxy_2: DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
```

Note that there are 2 DynamicProxyGenAssembly2es. One that lacks a public key, and the `*DataService`  fakes live there. One that has a public key, where the faked `Object` lives. I wonder if we're not using the second assembly at all unless the `Object` has been faked, and in that case, the serialization code is grabbing the wrong DynamicProxyGenAssembly2 assembly when it wants to deserialize the services.

I can take a deeper look over the next couple days as time allows.

**Comment by fishie** [comment] 2020-12-06 17:29
Nice work! I have just recently had a son so I haven't had time to spend on this. I remember that my next step was to ask Rebus people if they can see anything or help me remove Rebus from the equation because I was unable to. When I have some time between the screaming I will.

**Comment by blairconrad** [comment] 2020-12-06 19:02
Oh, congratulations, @fishie, and good luck!

**Comment by blairconrad** [comment] 2020-12-21 03:35
Hey! Remember my guess about the duplicate assemblies, differing only by public key, causing the problem. It's been more than "a couple of days", but I got back into it. I was right. 😮 

Anyhow, this change to Rebus.TestHelpers 

```diff
diff --git a/Rebus.TestHelpers/Internals/InMemorySagaStorage.cs b/Rebus.TestHelpers/Internals/InMemorySagaStorage.cs
index f1d04f7..c234075 100644
--- a/Rebus.TestHelpers/Internals/InMemorySagaStorage.cs
+++ b/Rebus.TestHelpers/Internals/InMemorySagaStorage.cs
@@ -23,7 +23,8 @@ namespace Rebus.TestHelpers.Internals

         readonly JsonSerializerSettings _serializerSettings = new JsonSerializerSettings
         {
-            TypeNameHandling = TypeNameHandling.All
+            TypeNameHandling = TypeNameHandling.All,
+            TypeNameAssemblyFormatHandling = TypeNameAssemblyFormatHandling.Full,
         };

         internal IEnumerable<ISagaData> Instances
```

makes `InMemorySagaStorage.Clone` produce

```json
{
    "$type": "MyProject.MySagaData, MyProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
    "SomeData": {
        "$type": "MyProject.SomeData, MyProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
        "Id": null
    },
    "SomeOtherData": {
        "$type": "Castle.Proxies.SomeOtherDataProxy, DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"
    },
    "Id": "2f8ba26d-636f-44c1-8f85-b450baebca3d",
    "Revision": 0
}
```

And then my test passes.

I suppose one could make the case that it's weird for Castle.Core (and by extension FakeItEasy) to produce two assemblies, differing only by public key, but I'm not sure anything would change. Me, I'd consider pursuing a fix in Rebus.TestHelpers.

**Comment by fishie** [comment] 2020-12-21 10:23
**Genius!**

I have confirmed that the change does work and I will create a pull request to Rebus.TestHelpers right away! So if I understand correctly the problem is that Castle.Core creates dynamic assemblies that sometimes have a public key and sometimes do not and xUnit will run unit tests in parallel which can result in a situation where there are two dynamic assemblies with the same name but different public key at the same time which messes up Assembly.LoadWithPartialName that Newtonsoft uses. So we can circumvent the issue by telling Newtonsoft to include the full assembly name when serializing. Is that correct? So in the end the issue was between Newtonsoft and Castle and not directly with FakeItEasy and Rebus at all. Great work @blairconrad. Merry christmas or God Jul as we say here!

**Comment by blairconrad** [comment] 2020-12-21 12:16
Thanks, @fishie, yup, your summary seems good. The only thing I'd possibly add is that I think that Castle.Core creates the assemblies with a public key when it's asked to proxy a type from an assembly that itself has a public key (as `object` is), and otherwise will not. I've not tried this out, but my guess is that if you instead strong-named the assembly that contained `SomeOtherData`, the problem may also go away.

Okay. Since FakeItEasy doesn't seem to be the problem, I think we can close this issue. Thanks for raising it, fishie. Happy FakeItEasying and God Jul.

**Closed** 2020-12-21 12:17 UTC
Labels: :speech_balloon:  discussion
