### ISSUE TITLE
Invoking asynchronous code

### ISSUE THREAD

**Issue by CedricHg** [FakeItEasy/FakeItEasy#1401] opened 2018-08-02 19:30 UTC
At the moment it's possible to invoke custom code by passing an Action via .Invokes. 
This works for synchronous code, but as an Action doesn't have a return value, it can't result in an awaitable task.

I have encountered a situation where such a situation would be handy - I'm supposed to unit test a class that should throw a timeout in a multithreaded context. Thread.Sleep is not helping me here, I have to be able to use Task.Delay.

To my understanding, the input parameters and return value of any Func need to be known at compile time, it's not possible to use generics. I'd propose to keep it simple, an have an overload accepting `Func <Task>` as a parameter.

**Comment by blairconrad** [comment] 2018-08-02 19:52
Hey, @CedricHg. Are you able to provide a small (yet complete) example of what you're trying to test, along with a sketch of how you'd imagine a test looking?

**Comment by CedricHg** [comment] 2018-08-02 21:04
Hi @blairconrad,

Turns out the issue isn't with FakeItEasy after all, I'll explain below, but first some code for context. This is the problem reduced to its simplest form:
`
var allowed = _semaphore.Wait(1000); // waits 1 sec, returns false if no response after 1 second

if (allowed)
{
	await _injectedInterface.SomeAsyncMethod();
}
else
{
	throw new TimeoutException();
}
`
My unit test passes a fake for _injectedInterface, and Invokes Thread.Sleep(3000) when SomeAsyncMethod is called. In the unit test I execute this code in 2 threads. The idea was that the first thread succeeds, and the second thread goes into timeout. 

When posting this, I encountered that both threads succeeded, leading me to believe the Thread.Sleep wasn't working, and that I needed to do an asynchronous Task.Delay call.

After posting I figured it doesn't make sense that Thread.Sleep wasn't working for me when invoking and researched it further. I gave my Threads a unique name and covered the code in Debug.WriteLines and it revealed that, even with an invoke of Thread.Sleep, the second thread indeed went into timeout.

However the exception wasn't properly propagated to the unit test. Now, the unit test, again reduced to the relevant code, looks like this:

`
[TestMethod]
[ExpectedException(typeof(TimeoutException))]
public async Task TestTimeout()
{
	var tasks = new Task[2];
	for (var i = 0; i < tasks.Count(); i++)
	{
		tasks[i] = _sut.ExecuteMethodAsync();
	}
	await Task.WhenAll(tasks);
}
`

You'll notice that in the loop I am not awaiting the task. Instead, I await the array via Task.WhenAll. My expectation was that the TimeoutException would've been returned by Task.WhenAll, but it doesn't return any exception, not even an AggregateException.

Putting the await in the loop (and thus, awaiting the tasks one by one) then DID propagate the TimeoutException back to the unit test.

I don't yet understand why the code above, using Task.WhenAll, doesn't work like I expect it to. I'll research this further and I can let you know my findings if you're interested - or you can just tell me if you already know the problem.

Either case, it's not an issue with FakeItEasy. My use case for wanting to invoke asynchronous code no longer stands, the issue can probably be closed.

**Comment by blairconrad** [comment] 2018-08-03 16:24
Sorry, @CedricHg. I poked around a little, but my .NET knowledge peaked around .NET 1.1, and I was not able to reproduce your problem. I wish you luck, but as you suggest, it seems not to be FakeItEasy-related, so closing.

**Closed by blairconrad** 2018-08-03 16:24 UTC
Labels: :speech_balloon:  discussion
