### ISSUE TITLE
Invoke method after calling an Entities public method/behaviour

### ISSUE THREAD

**Issue by FV-Transfero** [FakeItEasy/FakeItEasy#1990] opened 2024-03-28 15:49 UTC
I am attempting to use Invoke() after configuring a CallTo() on an Entities public method.
The workflow is I get an Entity from my database mocking the CallTo() a repository, then in my code I perform some operations calling a method, but for testing purposes I need to perform a transformation on this entity after this method is called, such as the following:

```
Foo foo = _fooRepos.GetById(id);
foo.DoSomething(bool aBool, string aString); // returns void
// rest of the code
```

I need to do something in the fashion of:

```
A.CallTo(() => _fooRepos.GetById(A<Guid>._).ReturnsLazily(...)
A.CallTo(() => A.Fake<Foo>().DoSomething(A<bool>._, A<string>._)).Invokes((Foo foo) => 
    {
        ...
    });
```
   
However, FakeItEasy does not allow me to do this. Is there any way (other than creating a stub) using FakeItEasy that allows me to do something similar to what I was attempting?

**Comment by blairconrad** [comment] 2024-03-28 18:13
Hi, @FV-Transfero. If I read you right, you're looking for something like

```csharp
var foo =  A.Fake<Foo>();
A.CallTo(() => A.Fake<Foo>().DoSomething(A<bool>._, A<string>._)).Invokes((Foo foo) => 
    {
        ...
    });
A.CallTo(() => _fooRepos.GetById(A<Guid>._).Returns(foo);
```

**Comment by FV-Transfero** [comment] 2024-03-28 18:33
Yes, that's it, after I get the desired entity from the database (mocked, of course), my code calls 'DoSomething()', which is a method present inside the entities class code block. But right after this call, I need to configure the result of calling this method (DoSomething()) so it forces a failure that will be caught on another section of my code, but since 'DoSomething()' is only declared 'public void', FakeItEasy doesn't seem to allow me to do the 'Invokes()' on it.

I was able to go around this issue and get the outcome I desired, but I wish to understand a bit more as to why I wasn't able to call Invokes on that particular method.

(Sorry if I wasn't clear enough, any other questions I'll try to answer to the best of my abilities)

**Comment by thomaslevesque** [comment] 2024-03-28 19:31
I might have misunderstood. If you want to cause a side effect when `DoSomething` is called, then the method needs to be virtual, otherwise FakeItEasy can't change its behavior. If you make it virtual but want to keep its original behavior, you can do this;

```
A.CallTo(() => foo.DoSomething(...)).CallsBaseMethod().Invokes(...)
```

**Comment by blairconrad** [comment] 2024-03-28 20:03
(something I had in flight when I saw @thomaslevesque's response)

>  I wish to understand a bit more as to why I wasn't able to call Invokes on that particular method.

I am going to need you to explain more about this. How were you not able? Compiler prevented you from writing the code? You attempted to configure the Fake but it didn't do what you expected? For me this works (throws an exception):


```csharp
public interface IFoo
{
    void DoSomething(bool b, string s);
}
[Fact]
public void Test1()
{
    var foo = A.Fake<IFoo>();
    A.CallTo(() => foo.DoSomething(A<bool>._, A<string>._))
        .Invokes((bool b, string s) => throw new Exception("I was invoked"));
    foo.DoSomething(true, "true");
}
```

If indeed your method is virtual, and it wasn't the compiler shutting you down, I suspect the problem is that you configured a Fake and threw it away:


```csharp
A.CallTo(() => A.Fake<Foo>().DoSomething(A<bool>._, A<string>._)).Invokes((Foo foo) => 
```

`A.Fake<Foo>()` is created, configured, and... that's it. It's never used for anything. Whereas you have another Foo (or fake Foo) that you returned from the repository that you never configured.

**Comment by blairconrad** [comment] 2024-03-28 20:03
Aaaaand I only saw the _second_ of @thomaslevesque's responses. I see he already mentioned the "thrown away Fake Foo" :blush:

**Comment by blairconrad** [comment] 2024-04-05 21:03
@FV-Transfero, has everything been addressed to your satisfaction? If there's nothing further, I'll close this issue

**Closed** 2024-04-18 03:19 UTC
