### ISSUE TITLE
prepare_release should create release branch as release-x.y.z, not release/x.y.z

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1228] opened 2017-10-10 15:16 UTC
As reported in https://github.com/FakeItEasy/FakeItEasy/pull/1225#issuecomment-335502288. 
It _seems_ the `/` was causing AppVeyor grief. Not sure why, but using `-` is no hardship.

**Comment by thomaslevesque** [comment] 2017-10-11 09:39
As demonstrated in #1229, the problem doesn't seem to be caused by the `/`... so changing `/` to `-` doesn't guarantee we won't have the problem again.

According to [this](http://help.appveyor.com/discussions/problems/4830-stuck-on-appveyor-was-unable-to-build-non-mergeable), the "AppVeyor was unable to build non-mergeable pull request" error could be transient, and retrying would probably have solved it.

I'm putting this issue `on-hold` until we have a better understanding of what the problem really is.

**Comment by blairconrad** [comment] 2017-10-19 02:09
Latest release released even with the `/`. I think we can close this.

**Comment by thomaslevesque** [comment] 2017-10-19 07:45
Indeed. I'll close it now.

**Closed by thomaslevesque** 2017-10-19 07:45 UTC
Labels: build, on-hold
