### ISSUE TITLE
MustHaveHappened fails if object updated after call been made

### ISSUE THREAD

**Issue by dhelper** [FakeItEasy/FakeItEasy#1394] opened 2018-07-09 13:04 UTC
I need to check if a specific call was made. In the method under test the same object is passed as a parameter to the test, then updated:
```
public void Func()
{
    var myDataClass = new MyDataClass();

    myDataClass.Value = 1;

    _dependecy.Foo(myDataClass);

    myDataClass.Value = 2;

    //... more code
}
```
_MyDataClass_ overrides both _IsEquals_ and _ToString_. If two instances have the same _Value_ they are equal to one another
The following test fails:
```
[Test]
public void Test()
{
    var fakeDependecy = A.Fake<IDependecy>();
    var myClass = new MyClass(fakeDependecy);

    myClass.Func();

    var expected = new MyDataClass{Value = 1};
    A.CallTo(() => fakeDependecy.Foo(expected)).MustHaveHappened();
}
```
With the error message:
> Message: FakeItEasy.ExpectationException : 
> 
>   Assertion failed for the following call:
>     ClassLibrary5.IDependecy.Foo(myDataClass: Value: 1)
>   Expected to find it once or more but didn't find it among the calls:
>     1: ClassLibrary5.IDependecy.Foo(myDataClass: Value: 2)

BTW
I have a workaround for this, I'm using "Invoke" to capture the variable as the method is called.

**Comment by blairconrad** [comment] 2018-07-09 13:09
Thanks for raising this, @dhelper. It is [known behaviour](http://fakeiteasy.readthedocs.io/en/stable/assertion/#asserting-calls-made-with-mutable-arguments), very difficult to change, and you're using one of the established workarounds.

**Comment by blairconrad** [comment] 2018-07-09 13:13
Closing, as this is a duplicate of #306.

**Closed by blairconrad** 2018-07-09 13:13 UTC

**Comment by thomaslevesque** [comment] 2018-07-09 13:17
> If two instances have the same `Value` they are equal to one another

You probably shouldn't do this with a mutable object. When you override `Equals`, you must also override `GetHashCode`, using the same logic (i.e. two objects that are considered equal should have the same hashcode). But if you base your equality/hashcode logic on mutable members, it means that your hashcode isn't constant. This can cause big issues if you use the class in a `HashSet` or as a key in a dictionary.

**Comment by dhelper** [comment] 2018-07-09 14:38
Thanks for the quick reply, obviously the real issue is the mutable code (BTW GetHashCode was overridden) but since the code writer cannot change the code at the moment as he would have liked to his only option is to record the call himself (using Invokes).

Cheers
