### ISSUE TITLE
ArgumentException in ChildScope.OnAddInterceptedCall()

### ISSUE THREAD

**Issue by breischl** [FakeItEasy/FakeItEasy#547] opened 2015-09-28 16:02 UTC
I am sometimes getting the following exception in some of my tests. The test has multiple concurrent `Task`s calling into the same faked method, and the error occurs intermittently and unpredictably, which leads me to suspect that it may be a concurrency issue. 

Given that the error is in `Dictionary`, and that the `ChildScope` class [does not appear to have any locking around its Dictionaries](https://github.com/FakeItEasy/FakeItEasy/blob/bd57a05c0de5ff37609230fd1b8bc4ec45bc9d4d/Source/FakeItEasy/Core/FakeScope.cs#L170), I expect that's most likely the problem. 

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at FakeItEasy.Core.FakeScope.ChildScope.OnAddInterceptedCall(FakeManager fakeManager, ICompletedFakeObjectCall call)
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IWritableFakeObjectCall fakeObjectCall)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ObjectProxy_6.UserMethod(String userMethodParam)
   <SNIP irrelevant user code>
   --- End of inner exception stack trace ---
   at UserClass.<UserMethod>d__21.MoveNext() in C:\UserClass.cs:line 365
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at UserClass.<UserMethod>d__20.MoveNext() in C:\UserClass.cs:line 128
```

**Comment by blairconrad** [comment] 2015-09-28 19:36
@breischl. I bet you're right. We know that scopes aren't particularly threadsafe, as mentioned in #484.
But the area you pointed out looks like a real problem!

**Comment by adamralph** [comment] 2016-01-09 18:29
Is this a duplicate of https://github.com/FakeItEasy/FakeItEasy/issues/484 ?

**Comment by blairconrad** [comment] 2016-01-10 02:56
They could be lumped together, but this is an error could occur when we (intentionally, even) use a single instance of `ChildScope` from multiple threads. Not when we unintentionally swap in a scope that will usurp the one that should've been  used in another thread.
We could rename #484 to be more specific.

**Comment by adamralph** [comment] 2016-03-07 06:41
Invalidated by #604

**Closed by adamralph** 2016-03-07 06:41 UTC
Labels: bug, invalid, P2
